name: Build and Test

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.8.0
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: pnpm
        cache-dependency-path:  |
          pnpm-lock.yaml
          frontend/pnpm-lock.yaml
          frontend/cdk/pnpm-lock.yaml
          backend/pnpm-lock.yaml

    - name: Build
      env:
        CI: true
      run: pnpm build
